title: Gnosis
subtitle: "Conditional tokens for the brave, true or false"
description: "The MultiToken Statndard (EIP-1155) allows us to build unique economies at scale. Learn how to here."
author: Gnosis
timezone: UTC

language:
  - en
locale: en
i18n:
  type: [page, post]
permalink_defaults:
  lang: en
i18n_dir: :lang

url: https://andytudhope.github.io
root: /conditional-token-docs/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

highlight:
  enable: false

theme: navy
deploy:
  type: git
  repo: git@github.com:andytudhope/conditional-token-docs.git
  branch: gh-pages

disqus_shortname: hexojs
twitter: cryptowanderer
github: andytudhope

graphviz:
  enable: true

mermaid:
  enable: true
  version: "7.1.2"
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js

math:
  engine: 'mathjax' # or 'katex'
  mathjax:
   # src: custom_mathjax_source
   # config: MathJax config
  katex:
   # css: custom_css_source
   # config: KaTeX config
